// <auto-generated />
using CODE_FIRST.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CODE_FIRST.Migrations
{
    [DbContext(typeof(StdContext))]
    [Migration("20230507142959_School")]
    partial class School
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CODE_FIRST.Models.Std", b =>
                {
                    b.Property<int>("stdRoll")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stdRoll"));

                    b.Property<string>("stdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stddept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("stdRoll");

                    b.ToTable("stds");
                });
#pragma warning restore 612, 618
        }
    }
}
